services:
  # A web service for the Password Manager
  - type: web
    name: password-manager
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1